### ISSUE TITLE
Book Store App demo

### ISSUE THREAD

**Issue by RummanUK** [tanjinbd/UI-UXDemo#1]
The demo screen looks very promising, Can I get the code to look at? Which language the application is created? Can it render PDF file also? Also if there is chance to include pdf and epub in to the library?

**Comment by tanjinbd** [comment]
Well, okay will upload the book application code as a different project.

As per current development status, the system supports following:
1. Dynamic Rendering of PDF
2. Adding PDF from device internal storage
3. listing books from a server
4. The system doesnt support epub yet, I am having difficulties epub rendering. Working with the code for future builds

**Comment by RummanUK** [comment]
I have a epub rendering project, let me share it here:
https://github.com/JSpiner/epub-viewer

This one also has paginator, viewer; will be cool to include few functions from here

Like listing:
list(APPEND NBL_CMAKE_ARGS "-DNBL_BUILD_DOCS:BOOL=OFF") # enable only if you have doxygen installed and detectable by cmake
list(APPEND NBL_CMAKE_ARGS "-DNBL_BUILD_EXAMPLES:BOOL=OFF")

**Comment by tanjinbd** [comment]
Thanks! Appreciate it:

But I have seen the project has searching bugs. Also listing doesnt work properly. Let me identify and try to fix those issue and eventually ePub rendering can be added.

Perhaps using static variable when listing fixes some issues:

Example:
list(APPEND NBL_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:PATH=${NBL_INSTALL_DIR}") # because of https://gitlab.kitware.com/cmake/cmake/-/issues/18790

ExternalProject_Add(Nabla
    DOWNLOAD_COMMAND  ""
    SOURCE_DIR        "${NBL_SOURCE_DIR}"
    BINARY_DIR        "${NBL_BINARY_DIR}"
    CMAKE_ARGS        ${NBL_CMAKE_ARGS}
    TEST_COMMAND      ""
)x
